export const books = [
  {
    id: 1,
    title: "The Midnight Library",
    author: "Matt Haig",
    price: 14.99,
    inStock: true,
    genre: "Fiction",
    isFavorite: true,
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    price: 18.0,
    inStock: true,
    genre: "Self-Help",
    isFavorite: false,
  },
  {
    id: 3,
    title: "Becoming",
    author: "Michelle Obama",
    price: 22.5,
    inStock: false,
    genre: "Biography",
    isFavorite: true,
  },
  {
    id: 4,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    price: 12.99,
    inStock: true,
    genre: "Thriller",
    isFavorite: false,
  },
  {
    id: 5,
    title: "Educated",
    author: "Tara Westover",
    price: 15.75,
    inStock: true,
    genre: "Memoir",
    isFavorite: false,
  },
  {
    id: 6,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: 19.99,
    inStock: false,
    genre: "History",
    isFavorite: false,
  },
  {
    id: 7,
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    price: 13.49,
    inStock: true,
    genre: "Mystery",
    isFavorite: false,
  },
  {
    id: 8,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 10.0,
    inStock: true,
    genre: "Philosophy",
    isFavorite: false,
  },
  {
    id: 9,
    title: "Dune",
    author: "Frank Herbert",
    price: 17.95,
    inStock: false,
    genre: "Science Fiction",
    isFavorite: false,
  },
  {
    id: 10,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    price: 16.0,
    inStock: true,
    genre: "Self-Help",
    isFavorite: false,
  },
];
